### ISSUE TITLE
113 warning on heuristic usage

### ISSUE THREAD

**Issue by zkat** [pornel/http-cache-semantics#3]
The spec requires that a 113 warning code be added to the response if revalidation used heuristics. There doesn't seem to be any way for external libraries to detect whether http-cache-semantics used these heuristics, either.

**Comment by pornel** [comment]
OK, I think I can add it automatically to `.responseHeaders()`.

I'm not sure where to plug it internally, since ttl is used indirectly in a few places.

**Comment by pornel** [comment]
Done in a897f6844596e003a877979c6f94ed230b4561dc
