### ISSUE TITLE
Version 3.8.0 throws error in npm run build

### ISSUE THREAD

**Issue by Peak7Solutions** [pornel/http-cache-semantics#6]
using reference: 
  "http-cache-semantics": "3.8.0",
causes the following error: 
![image](https://user-images.githubusercontent.com/32751437/31519858-aa056004-af58-11e7-8b1a-7fa422afe8c8.png)

ERROR in bundle.js from UglifyJs
SyntaxError: Unexpected character '`' [./~/http-cache-semantics/node4/index.js:279,0]
[13:41:33] Finished 'buildWebpack' after 39 s
[13:41:33] Finished 'html' after 40 s

**Comment by pornel** [comment]
The code is for Node 4 and later, which means it requires ES6 and will not work with ES5-only tools. 

You probably need either https://www.npmjs.com/package/uglify-es or Babel to convert it to the old JS for Uglify first.
